### ISSUE TITLE
parameters 

### ISSUE THREAD

**Issue by antonysama** [kaobeosolu78/Scientific_Study_Analysis#2]
A few more questions if I may. What is the correct order of running the three python  files (is it 'get_sci_study', 'processing', and 'study') ? 

In 'get_sci_study' what does the second last parameter do (med = load_obj(' tobacco') ? 

Other than in the 'get_sci_study', are there parameters one needs to change in the other two files ?

What are the expected outputs (is it the pkl files)?

Thank you.

**Comment by kaobeosolu78** [comment]
Get_sci_study, then processing. Study is for holding class containers for various files that has yet to be implemented.

Med is just a temporary variable I had to load previous studies I had gotten to both make sure everything was downloading properly and to begin testing of the processing functions. 

Chromedriver and kw(keyword) should be the only parameters that need to be changed. I usually have my outputs as pkl files to save on space and because they are relatively easy to work with.

I apologize for the lack of commenting, the whole thing is far from where I would like it to be as of now but I haven't had much time for adding to it due to school. Feel free to commit potential changes and lmk if you have any questions.

**Comment by antonysama** [comment]
Thank you again and this is now clear to me. Your code works fine and I don't have any commits to add. The issues I raised and your responses may suffice for other potential users.
